### ISSUE TITLE
nodes are available: 7 node(s) didn't match node selector

### ISSUE THREAD

**Issue by amw269756** [huanwei/rocketmq-operator#44] opened 2019-08-05 06:49 UTC
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- RocketMQ Operator version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by huanwei** [comment] 2019-09-05 07:15
@amw269756 Sorry for the late response. Can you share more details.  I guess It should be caused by `nodeSelector` in the name server config. Or please try the latest version.

**Comment by huanwei** [comment] 2019-09-24 18:32
I will close this issue @amw269756

**Comment by blackist** [comment] 2020-04-10 12:28
I delete two lines in 03-deploymentWithConfig.yaml, it works: 
```
nodeSelector:
        rocketmq-operator: "on"
```

**Comment by huanwei** [comment] 2020-08-13 02:33
@blackist thanks. closing

**Closed as completed** 2020-08-13 02:33 UTC
